# -*- coding: utf-8 -*-
"""Supply_Chain_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Uday0312/Black-Friday__-sales__-Data_-analysis/blob/main/Supply_Chain_Analysis.ipynb
"""

from google.colab import drive

drive.mount('/content/drive')

df = pd.read_csv ("/content/drive/MyDrive/supply_chain_data.csv")

print(df.head())

print(df.describe())

"""#relationship between the price of the products and the revenue generated"""



fig = px.scatter(df, x='Price',
                 y='Revenue generated',
                 color='Product type',
                 trendline="ols")

fig.show()

#sales by product type:

sales_df= df.groupby('Product type') ['Number of products sold'].sum().reset_index()
pie_chart = px.pie(sales_df, values='Number of products sold', names='Product type',
                   title='Sales by Product Type',
                   hover_data=['Number of products sold'],
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition ='inside', textinfo='percent+label')
pie_chart.show()

"""#total revenue generated from shipping carriers:"""

total_revenue = df.groupby('Shipping carriers') ['Revenue generated'].sum().reset_index()
 fig = go.Figure()
 fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                     y=total_revenue['Revenue generated']))
 fig.update_layout(title='Total Revenue by Shipping Carrier',
                  xaxis_title='Shipping Carrier',
                  yaxis_title='Revenue Generated')
fig.show()

"""**Average lead time and Average Manufacturing Costs for all products of the company**"""

avg_lead_time = df.groupby('Product type')['Lead time'].mean().reset_index()
avg_manufacturing_costs = df.groupby('Product type')['Manufacturing costs'].mean().reset_index()
result = pd.merge(avg_lead_time,avg_manufacturing_costs,on = 'Product type')
result.rename(columns={'Lead time':'Average Lead Time','Manufacturing costs': 'Average Manufacturing costs' },inplace = True )
print(result)

"""**Analyzing Stock Keeping Units**"""

revenue_chart = px.line(df, x='SKU',y='Revenue generated',title='Revenue Generated by SKU' )

revenue_chart.show()



"""**Stock levels**

"""

stock_chart = px.line(df,x='SKU',y= 'Stock levels',title= 'Stock levels by SKU' )

stock_chart.show()



"""**Order Quantity of each SKU**"""

Order_Quantity = px.bar(df,x='SKU',y='Order quantities',title='Order_Quantity by SKU')

Order_Quantity.show()

"""**Cost Analysis**

**analyze the shipping cost of Carriers:**
"""

shipping_cost_chart= px.bar(df,x='Shipping carriers',y='Shipping costs',title = 'Shipping cost of Carriers:')

shipping_cost_chart.show()



"""**cost distribution by transportation mode**"""

transportation_chart = px.pie(df,values = 'Costs',names='Transportation modes',title= 'Cost Distribution by Transportation Mode', hole=0.5)

transportation_chart.show()



"""**Analyzing Defect Rate**"""

defect_rates_by_product = df.groupby('Product type')['Defect rates'].mean().reset_index()
fig = px.bar(df,x='Product type',y='Defect rates',title = 'Defect rate by product')

fig.show()

